# Setup
title:               PLUS ULTRA
tagline:             '나며기의 Tech Blog'
description:         '안녕하세요.'
url:                 https://skaurl.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              김남혁
  url:
  email:             dr_lunars@naver.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: UA-201810935-1
